version: 2.1

jobs:
  install-dependencies:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y webp
            pip install awscli boto3 pillow

workflows:
  version: 2
  convert-and-deploy:
    jobs:
      - install-dependencies
