version: 2.1

jobs:
  install-dependencies:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y webp
            pip install awscli boto3 pillow

  configure-aws:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Configure AWS CLI
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            echo "[default]" > ~/.aws/config
            echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config

workflows:
  version: 2
  convert-and-deploy:
    jobs:
      - install-dependencies
      - configure-aws:
          requires:
            - install-dependencies