version: 2.1

jobs:
  install-dependencies:
    docker:
      - image: cimg/python:3.8
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install -y webp awscli
            pip install awscli boto3 pillow

  configure-aws:
    docker:
      - image: cimg/python:3.8
    resource_class: small
    steps:
      - checkout
      - run:
          name: Configure AWS CLI
          command: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            echo "[default]" > ~/.aws/config
            echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config
  
  test-aws-ls:
    docker:
      - image: cimg/python:3.8
    resource_class: small
    steps:
      - checkout
      - run:
          name: Test Aws Access
          command: |
            aws --profile wasabi-circleci s3 ls --endpoint-url https://s3.ap-northeast-1.wasabisys.com assets.potapoyo.com/


workflows:
  version: 2
  convert-and-deploy:
    jobs:
      - install-dependencies
      - configure-aws:
          requires:
            - install-dependencies
      - test-aws-ls:
          requires:
            - configure-aws