version: 2.1

executors:
  default:
    docker:
      - image: "cimg/python:3.12"
    resource_class: small

commands:
  install_dependencies:
    steps:
      - run:
          name: Install AWS CLI
          command: |
            sudo apt update
            sudo apt install -y awscli
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            echo "[default]" > ~/.aws/config
            echo "region = $AWS_DEFAULT_REGION" >> ~/.aws/config

  awss3_list_bucket:
    steps:
      - run:
          name: List S3 Bucket
          command: |
            aws s3 ls --endpoint-url https://$AWS_ENDPOINT_URL $AWS_BUCKET_NAME/

jobs:
  check_s3_bucket:
    executor: default
    steps:
      - install_dependencies
      - awss3_list_bucket

workflows:
  check_and_list:
    jobs:
      - check_s3_bucket