version: 2.1

executors:
  default:
    docker:
      - image: "cimg/aws:2024.03.1"
    resource_class: small

commands:
  awss3_list_bucket:
    steps:
      - run:
          name: List S3 Bucket
          command: |
            aws s3 ls --endpoint-url https://$AWS_ENDPOINT_URL $AWS_BUCKET_NAME/

jobs:
  check_s3_bucket:
    executor: default
    steps:
      - awss3_list_bucket

workflows:
  check_and_list:
    jobs:
      - check_s3_bucket